// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ConfigurationWebApiService.Models
{
    public partial class ColourSchemas
    {
        public ColourSchemas(ColourSchemas cs)
        {
            Id = cs.Id == Guid.Empty ? Guid.NewGuid() : cs.Id;
            Title = cs.Title;
            Description = cs.Description;
            Value=cs.Value;

        }
        public ColourSchemas(string title, string description, string value)
        {
            Title = title;
            Description = description;
            Value = value;
        }
        public ColourSchemas()
        {
            ColourSchemaConfiguration = new HashSet<ColourSchemaConfiguration>();
        }

        [Key]
        public Guid Id { get; internal set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; } = default!;
        public string? Description { get; set; }
        [Required]
        public string Value { get; set; } = default!;

        [InverseProperty("ColourSchema")]
        public virtual ICollection<ColourSchemaConfiguration> ColourSchemaConfiguration { get; set; }
    }
}