// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ConfigurationWebApiService.Models
{
    public partial class ColourSchemaConfiguration
    {
        [Key]
        public Guid Id { get; set; }
        public Guid ColourSchemaId { get; set; }
        public Guid ConfigurationId { get; set; }

        [ForeignKey(nameof(ColourSchemaId))]
        [InverseProperty(nameof(ColourSchemas.ColourSchemaConfiguration))]
        public virtual ColourSchemas ColourSchema { get; set; } = default!;
        [ForeignKey(nameof(ConfigurationId))]
        [InverseProperty(nameof(Configurations.ColourSchemaConfiguration))]
        public virtual Configurations Configuration { get; set; } = default!;
    }
}