// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ConfigurationWebApiService.Models;

public partial class ColourSchemaConfiguration
{
    [Key]
    public Guid Id { get; set; }

    public Guid ColourSchemaId { get; set; }

    public Guid ConfigurationId { get; set; }

    [ForeignKey("ColourSchemaId")]
    [InverseProperty("ColourSchemaConfiguration")]
    public virtual ColourSchemas ColourSchema { get; set; } = null!;

    [ForeignKey("ConfigurationId")]
    [InverseProperty("ColourSchemaConfiguration")]
    public virtual Configurations Configuration { get; set; } = null!;
}