// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;

#nullable enable

namespace ConfigurationWebApiService.Models
{
    public partial class ColourSchemaConfiguration
    {
        public ColourSchemaConfiguration(ColourSchemaConfiguration csc, [CallerMemberName] string caller = "")
        {
            Id = csc.Id == Guid.Empty ? Guid.NewGuid() : csc.Id;
            ColourSchemaId = csc.ColourSchemaId;
            ConfigurationId = csc.ConfigurationId;
        }
        public ColourSchemaConfiguration(Guid colorSchemaId, Guid configurationId)
        {
            Id= Guid.NewGuid();
            ColourSchemaId= colorSchemaId;
            ConfigurationId= configurationId;
        }
        public ColourSchemaConfiguration()
        {
            
        }
        [Key]
        public Guid Id { get; internal set; }
        public Guid ColourSchemaId { get; set; }
        public Guid ConfigurationId { get; set; }

        [ForeignKey(nameof(ColourSchemaId))]
        [InverseProperty(nameof(ColourSchemas.ColourSchemaConfiguration))]
        public virtual ColourSchemas ColourSchema { get; set; } = default!;
        [ForeignKey(nameof(ConfigurationId))]
        [InverseProperty(nameof(Configurations.ColourSchemaConfiguration))]
        public virtual Configurations Configuration { get; set; } = default!;
    }
}