// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

#nullable enable

namespace ConfigurationWebApiService.Models
{
    public partial class Configurations
    {
        public Configurations(string title, string description)
        {
            Id = Guid.NewGuid();
            Title = title;
            Description = description;
            CreateDate = DateTime.Now;
            UpdateDate = null;
            Version = 1;
            ColourSchemaConfiguration = new HashSet<ColourSchemaConfiguration>();
            FontConfiguration = new HashSet<FontConfiguration>();
            HotKeyConfigurations = new HashSet<HotKeyConfigurations>();
            UserConfiguration = new HashSet<UserConfiguration>();
            WindowLocationConfiguration = new HashSet<WindowLocationConfiguration>();
        }
        public Configurations()
        {
            ColourSchemaConfiguration = new HashSet<ColourSchemaConfiguration>();
            FontConfiguration = new HashSet<FontConfiguration>();
            HotKeyConfigurations = new HashSet<HotKeyConfigurations>();
            UserConfiguration = new HashSet<UserConfiguration>();
            WindowLocationConfiguration = new HashSet<WindowLocationConfiguration>();
        }

        [Key]
        public Guid Id { get; internal set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; } = default!;
        public string? Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; internal set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; internal set; }
        [IgnoreDataMember]
        public int Version { get; internal set; }
        [InverseProperty("Configuration")]
        public virtual ICollection<ColourSchemaConfiguration> ColourSchemaConfiguration { get; internal set; }
        [InverseProperty("Configuration")]
        public virtual ICollection<FontConfiguration> FontConfiguration { get; internal set; }
        [InverseProperty("Configuration")]
        public virtual ICollection<HotKeyConfigurations> HotKeyConfigurations { get; internal set; }
        [InverseProperty("Configuration")]
        public virtual ICollection<UserConfiguration> UserConfiguration { get; internal set; }
        [InverseProperty("Configuration")]
        public virtual ICollection<WindowLocationConfiguration> WindowLocationConfiguration { get; internal set; }
    }
}