// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;

#nullable enable

namespace ConfigurationWebApiService.Models
{
    public partial class EventSubscription
    {
        public EventSubscription(EventSubscription es, [CallerMemberName] string caller = "")
        {
            Id = es.Id == Guid.Empty ? Guid.NewGuid() : es.Id;
            CreateDate = es.CreateDate == DateTime.MinValue ? DateTime.Now : es.CreateDate;
            UpdateDate = caller.Contains("Add") ? null : DateTime.Now;
            Title = es.Title;
            Description = es.Description;
        }
        public EventSubscription()
        {
            SubscriptionEventSubscription = new HashSet<SubscriptionEventSubscription>();
        }

        [Key]
        public Guid Id { get; internal set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; } = default!;
        public string? Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; internal set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; internal set; }

        [InverseProperty("EventSubscription")]
        public virtual ICollection<SubscriptionEventSubscription> SubscriptionEventSubscription { get; set; }
    }
}