// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ConfigurationWebApiService.Models
{
    public partial class EventSubscription
    {
        public EventSubscription()
        {
            SubscriptionEventSubscription = new HashSet<SubscriptionEventSubscription>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; } = default!;
        public string? Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [InverseProperty("EventSubscription")]
        public virtual ICollection<SubscriptionEventSubscription> SubscriptionEventSubscription { get; set; }
    }
}