// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ConfigurationWebApiService.Models
{
    public partial class HotKeyConfigurations
    {
        [Key]
        public Guid Id { get; set; }
        public Guid HotKeyId { get; set; }
        public Guid ConfigurationId { get; set; }

        [ForeignKey(nameof(ConfigurationId))]
        [InverseProperty(nameof(Configurations.HotKeyConfigurations))]
        public virtual Configurations Configuration { get; set; } = default!;
        [ForeignKey(nameof(HotKeyId))]
        [InverseProperty(nameof(Hotkeys.HotKeyConfigurations))]
        public virtual Hotkeys HotKey { get; set; } = default!;
    }
}