// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ConfigurationWebApiService.Models;

public partial class Hotkeys
{
    public Hotkeys(Hotkeys hotkey)
    {
        Id = hotkey.Id == Guid.Empty ? Guid.NewGuid() : hotkey.Id; ;
        Title = hotkey.Title;
        Description = hotkey.Description;
        Value = hotkey.Value;
        HotKeyConfigurations = new HashSet<HotKeyConfigurations>();
    }
    public Hotkeys()
    {
        HotKeyConfigurations = new HashSet<HotKeyConfigurations>();
    }
    [Key]
    public Guid Id { get; set; }

    [StringLength(80)]
    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    public string Value { get; set; } = null!;

    [InverseProperty("HotKey")]
    public virtual ICollection<HotKeyConfigurations> HotKeyConfigurations { get; set; } = new List<HotKeyConfigurations>();
}