// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ConfigurationWebApiService.Models;

public partial class HotKeyConfigurations
{
    public HotKeyConfigurations()
    {

    }
    public HotKeyConfigurations(HotKeyConfigurations hotKeyConfiguration)
    {
        Id = hotKeyConfiguration.Id == Guid.Empty ? Guid.NewGuid() : hotKeyConfiguration.Id;
        HotKeyId = hotKeyConfiguration.HotKeyId;
        ConfigurationId = hotKeyConfiguration.ConfigurationId;
    }
    [Key]
    public Guid Id { get; set; }

    public Guid HotKeyId { get; set; }

    public Guid ConfigurationId { get; set; }

    [ForeignKey("ConfigurationId")]
    [InverseProperty("HotKeyConfigurations")]
    public virtual Configurations Configuration { get; set; } = null!;

    [ForeignKey("HotKeyId")]
    [InverseProperty("HotKeyConfigurations")]
    public virtual Hotkeys HotKey { get; set; } = null!;
}