// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ConfigurationWebApiService.Models
{
    public partial class Hotkeys
    {
        public Hotkeys()
        {
            HotKeyConfigurations = new HashSet<HotKeyConfigurations>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(80)]
        public string Title { get; set; } = default!;
        public string? Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        public bool IsActive { get; set; }

        [InverseProperty("HotKey")]
        public virtual ICollection<HotKeyConfigurations> HotKeyConfigurations { get; set; }
    }
}