// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ConfigurationWebApiService.Models;

public partial class SubscriptionEventSubscription
{
    public SubscriptionEventSubscription()
    {

    }
    public SubscriptionEventSubscription(SubscriptionEventSubscription subscriptionEventSubscription)
    {
        Id = subscriptionEventSubscription.Id == Guid.Empty ? Guid.NewGuid() : subscriptionEventSubscription.Id;
        SubscriptionId = subscriptionEventSubscription.SubscriptionId;
        EventSubscriptionId = subscriptionEventSubscription.SubscriptionId;
    }
    [Key]
    public Guid Id { get; set; }

    public Guid SubscriptionId { get; set; }

    public Guid EventSubscriptionId { get; set; }

    [ForeignKey("EventSubscriptionId")]
    [InverseProperty("SubscriptionEventSubscription")]
    public virtual EventSubscription EventSubscription { get; set; } = null!;

    [ForeignKey("SubscriptionId")]
    [InverseProperty("SubscriptionEventSubscription")]
    public virtual Subscriptions Subscription { get; set; } = null!;
}