// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ConfigurationWebApiService.Models
{
    public partial class SubscriptionEventSubscription
    {
        [Key]
        public Guid Id { get; set; }
        public Guid SubscriptionId { get; set; }
        public Guid EventSubscriptionId { get; set; }

        [ForeignKey(nameof(EventSubscriptionId))]
        [InverseProperty("SubscriptionEventSubscription")]
        public virtual EventSubscription EventSubscription { get; set; } = default!;
        [ForeignKey(nameof(SubscriptionId))]
        [InverseProperty(nameof(Subscriptions.SubscriptionEventSubscription))]
        public virtual Subscriptions Subscription { get; set; } = default!;
    }
}