// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;
using Microsoft.EntityFrameworkCore;

namespace ConfigurationWebApiService.Models;

public partial class UserTrackingObjectEventSubscription
{
    public UserTrackingObjectEventSubscription()
    {
    }
    public UserTrackingObjectEventSubscription(UserTrackingObjectEventSubscription utoes, [CallerMemberName] string caller = "")
    {
        Id = utoes.Id == Guid.Empty ? Guid.NewGuid() : utoes.Id;
        UserTrackingObjectId = utoes.UserTrackingObjectId;
        EventSubscriptionId = utoes.EventSubscriptionId;
    }
    [Key]
    public Guid Id { get; set; }

    public Guid UserTrackingObjectId { get; set; }

    public Guid EventSubscriptionId { get; set; }

    [ForeignKey("EventSubscriptionId")]
    [InverseProperty("UserTrackingObjectEventSubscription")]
    public virtual EventSubscription EventSubscription { get; set; } = null!;

    [ForeignKey("UserTrackingObjectId")]
    [InverseProperty("UserTrackingObjectEventSubscription")]
    public virtual UserTrackingObject UserTrackingObject { get; set; } = null!;
}