// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ConfigurationWebApiService.Models;

public partial class WindowLocations
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(50)]
    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    public Guid WindowId { get; set; }

    [Column("x", TypeName = "numeric(18, 0)")]
    public decimal? X { get; set; }

    [Column("y", TypeName = "numeric(18, 0)")]
    public decimal? Y { get; set; }

    [ForeignKey("WindowId")]
    [InverseProperty("WindowLocations")]
    public virtual Windows Window { get; set; } = null!;
}