// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ConfigurationWebApiService.Models
{
    public partial class WindowLocations
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; } = default!;
        public string? Description { get; set; }
        public Guid WindowId { get; set; }
        [Column("x", TypeName = "numeric(18, 0)")]
        public decimal? X { get; set; }
        [Column("y", TypeName = "numeric(18, 0)")]
        public decimal? Y { get; set; }

        [ForeignKey(nameof(WindowId))]
        [InverseProperty(nameof(Windows.WindowLocations))]
        public virtual Windows Window { get; set; } = default!;
    }
}