// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ConfigurationWebApiService.Models;

public partial class WindowLocationConfiguration
{
    [Key]
    public Guid Id { get; set; }

    public Guid? WindowLocationId { get; set; }

    public Guid ConfigurationId { get; set; }

    [ForeignKey("ConfigurationId")]
    [InverseProperty("WindowLocationConfiguration")]
    public virtual Configurations Configuration { get; set; } = null!;

    [ForeignKey("WindowLocationId")]
    [InverseProperty("WindowLocationConfiguration")]
    public virtual Fonts? WindowLocation { get; set; }
}