// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;

#nullable enable

namespace ConfigurationWebApiService.Models
{
    public partial class Windows
    {
        public Windows(Windows window)
        {
            Id = window.Id == Guid.Empty ? Guid.NewGuid() : window.Id;
            Title = window.Title;
            Handler = window.Handler;
            WindowLocations = new HashSet<WindowLocations>();
        }
        public Windows()
        {
            WindowLocations = new HashSet<WindowLocations>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; } = default!;
        [Required]
        public string Handler { get; set; } = default!;

        [InverseProperty("Window")]
        public virtual ICollection<WindowLocations> WindowLocations { get; set; }
    }
}